<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üöü ü§π üßëüèΩ‚Äçü§ù‚ÄçüßëüèΩ Exceptions Kotlin et leurs fonctionnalit√©s ü§º üóúÔ∏è ü•ò</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Notre entreprise utilise Kotlin en production depuis plus de deux ans. Personnellement, j'ai rencontr√© cette langue il y a environ un an. Il y a de no...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Exceptions Kotlin et leurs fonctionnalit√©s</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/maxilect/blog/447380/">  Notre entreprise utilise Kotlin en production depuis plus de deux ans.  Personnellement, j'ai rencontr√© cette langue il y a environ un an.  Il y a de nombreux sujets √† aborder, mais aujourd'hui nous parlerons de la gestion des erreurs, y compris dans un style fonctionnel.  Je vais vous dire comment faire cela √† Kotlin. <br><br><img src="https://habrastorage.org/webt/mb/bh/cp/mbbhcprsketr78wg8twpwhijg0y.jpeg" alt="image"><br><br>  <i>(Photo de la r√©union sur ce sujet, qui a eu lieu dans le bureau de l'une des soci√©t√©s Taganrog. Alexey Shafranov, chef du groupe de travail (Java) chez Maxilekt, a pris la parole)</i> <br><a name="habracut"></a><br><h3>  Comment g√©rer les erreurs en principe? </h3><br>  J'ai trouv√© plusieurs fa√ßons: <br><br><ul><li>  vous pouvez utiliser une <b>valeur de retour</b> comme pointeur sur le fait qu'il y a une erreur; </li><li>  vous pouvez utiliser <b>le param√®tre indicateur</b> dans le m√™me but, </li><li>  entrez une <b>variable globale</b> </li><li>  g√©rer les <b>exceptions</b> </li><li>  Ajouter des <b>contrats (DbC)</b> . </li></ul><br>  Arr√™tons-nous plus en d√©tail sur chacune des options. <br><br><h4>  Valeur de retour </h4><br>  Une certaine valeur ¬´magique¬ª est renvoy√©e en cas d'erreur.  Si vous avez d√©j√† utilis√© des langages de script, vous devez avoir vu des constructions similaires. <br><br>  Exemple 1: <br><br><pre><code class="plaintext hljs">function sqrt(x) { if(x &lt; 0) return -1; else return ‚àöx; }</code> </pre> <br>  Exemple 2: <br><br><pre> <code class="plaintext hljs">function getUser(id) { result = db.getUserById(id) if (result) return result as User else return ‚ÄúCan't find user ‚Äù + id }</code> </pre><br><h4>  Param√®tre indicateur </h4><br>  Un certain param√®tre pass√© √† la fonction est utilis√©.  Apr√®s avoir renvoy√© la valeur par le param√®tre, vous pouvez voir s'il y avait une erreur √† l'int√©rieur de la fonction. <br><br>  Un exemple: <br><br><pre> <code class="plaintext hljs">function divide(x,y,out Success) { if (y == 0) Success = false else Success = true return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4>  Variable globale </h4><br>  La variable globale fonctionne √† peu pr√®s de la m√™me mani√®re. <br><br>  Un exemple: <br><br><pre> <code class="plaintext hljs">global Success = true function divide(x,y) { if (y == 0) Success = false else return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4>  Exceptions </h4><br>  Nous sommes tous habitu√©s aux exceptions.  Ils sont utilis√©s presque partout. <br><br>  Un exemple: <br><br><pre> <code class="plaintext hljs">function divide(x,y) { if (y == 0) throw Exception() else return x/y } try{ divide(10, 0)} catch (e) {//handle exception}</code> </pre><br><h4>  Contrats (DbC) </h4><br>  Franchement, je n'ai jamais vu cette approche en direct.  Apr√®s une longue recherche sur Google, j'ai trouv√© que Kotlin 1.3 avait une biblioth√®que qui permet en fait l'utilisation de contrats.  C'est-√†-dire  vous pouvez d√©finir la condition sur les variables qui sont pass√©es √† la fonction, la condition sur la valeur de retour, le nombre d'appels, d'o√π elle est appel√©e, etc.  Et si toutes les conditions sont remplies, on pense que la fonction a fonctionn√© correctement. <br><br>  Un exemple: <br><br><pre> <code class="plaintext hljs">function sqrt (x) pre-condition (x &gt;= 0) post-condition (return &gt;= 0) begin calculate sqrt from x end</code> </pre><br>  Honn√™tement, cette biblioth√®que a une syntaxe terrible.  C'est peut-√™tre pour cela que je n'ai pas vu une telle chose en direct. <br><br><h3>  Exceptions en Java </h3><br>  Passons √† Java et comment tout cela a fonctionn√© depuis le d√©but. <br><br><img src="https://habrastorage.org/webt/gk/oo/mw/gkoomw72k7yp5mhpi9ebpt02g-i.png" alt="image"><br><br>  Lors de la conception d'une langue, deux types d'exceptions ont √©t√© pr√©vus: <br><br><ul><li>  v√©rifi√© - v√©rifi√©; </li><li>  non coch√©e - non coch√©e. </li></ul><br>  √Ä quoi servent les exceptions v√©rifi√©es?  Th√©oriquement, ils sont n√©cessaires pour que les gens doivent v√©rifier les erreurs.  C'est-√†-dire  si une certaine exception v√©rifi√©e est possible, elle doit √™tre v√©rifi√©e ult√©rieurement.  Th√©oriquement, cette approche aurait d√ª conduire √† l'absence d'erreurs non trait√©es et √† une meilleure qualit√© du code.  Mais en pratique, ce n'est pas le cas.  Je pense que tout le monde au moins une fois dans sa vie a vu un bloc de capture vide. <br><br>  Pourquoi cela peut-il √™tre mauvais? <br><br>  Voici un exemple classique directement de la documentation Kotlin - une interface du JDK impl√©ment√© dans StringBuilder: <br><br><pre> <code class="plaintext hljs">Appendable append(CharSequence csq) throws IOException; try { log.append(message) } catch (IOException e) { //Must be safe }</code> </pre><br>  Je suis s√ªr que vous avez rencontr√© beaucoup de code envelopp√© dans try-catch, o√π catch est un bloc vide, car une telle situation n'aurait tout simplement pas d√ª se produire, selon le d√©veloppeur.  Dans de nombreux cas, la gestion des exceptions v√©rifi√©es est impl√©ment√©e de la mani√®re suivante: elles l√®vent simplement une RuntimeException et l'attrapent quelque part au-dessus (ou ne l'attrapent pas ...). <br><br><pre> <code class="plaintext hljs">try { // do something } catch (IOException e) { throw new RuntimeException(e); //  - ...</code> </pre><br><h3>  Ce qui est possible √† Kotlin </h3><br>  En termes d'exceptions, le compilateur Kotlin est diff√©rent en ce que: <br><br>  1. Ne fait pas de distinction entre les exceptions coch√©es et non coch√©es.  Toutes les exceptions ne sont d√©coch√©es que et vous d√©cidez vous-m√™me de les intercepter et de les traiter. <br><br>  2. Try peut √™tre utilis√© comme expression - vous pouvez ex√©cuter le bloc try et en renvoyer la derni√®re ligne ou renvoyer la derni√®re ligne du bloc catch. <br><br><pre> <code class="plaintext hljs">val value = try {Integer.parseInt(‚Äúlol‚Äù)} catch(e: NumberFormanException) { 4 } // </code> </pre><br>  3. Vous pouvez √©galement utiliser une construction similaire lorsque vous faites r√©f√©rence √† un objet, qui peut √™tre annulable: <br><br><pre> <code class="plaintext hljs">val s = obj.money ?: throw IllegalArgumentException(‚Äú , ‚Äù)</code> </pre><br><h4>  Compatibilit√© Java </h4><br>  Le code Kotlin peut √™tre utilis√© en Java et vice versa.  Comment g√©rer les exceptions? <br><br><ul><li>  Les exceptions v√©rifi√©es de Java dans Kotlin ne peuvent √™tre ni v√©rifi√©es ni d√©clar√©es (car il n'y a pas d'exceptions v√©rifi√©es dans Kotlin). </li><li>  Les exceptions v√©rifi√©es possibles de Kotlin (par exemple, celles qui sont originaires de Java) ne doivent pas √™tre v√©rifi√©es en Java. </li><li>  S'il est n√©cessaire de v√©rifier, l'exception peut √™tre rendue v√©rifiable √† l'aide de l'annotation @Throws dans la m√©thode (il est n√©cessaire d'indiquer quelles exceptions cette m√©thode peut lever).  L'annotation ci-dessus est uniquement pour la compatibilit√© Java.  Mais en pratique, beaucoup de gens l'utilisent pour d√©clarer qu'une telle m√©thode, en principe, peut lever une sorte d'exception. </li></ul><br><h4>  Alternative au bloc try-catch </h4><br>  Le bloc try-catch pr√©sente un inconv√©nient important.  Lorsqu'il appara√Æt, une partie de la logique m√©tier est transf√©r√©e √† l'int√©rieur du crochet, et cela peut se produire dans l'une des nombreuses m√©thodes ci-dessus.  Lorsque la logique m√©tier est r√©partie sur des blocs ou sur toute la cha√Æne d'appels, il est plus difficile de comprendre le fonctionnement de l'application.  Et les blocs de lisibilit√© eux-m√™mes n'ajoutent pas de code. <br><br><pre> <code class="plaintext hljs">try { HttpService.SendNotification(endpointUrl); MarkNotificationAsSent(); } catch (e: UnableToConnectToServerException) { MarkNotificationAsNotSent(); }</code> </pre><br>  Quelles sont les alternatives? <br><br>  Une option nous offre une approche fonctionnelle de la gestion des exceptions.  Une impl√©mentation similaire ressemble √† ceci: <br><br><pre> <code class="plaintext hljs">val result: Try&lt;Result&gt; = Try{HttpService.SendNotification(endpointUrl)} when(result) { is Success -&gt; MarkNotificationAsSent() is Failure -&gt; MarkNotificationAsNotSent() }</code> </pre><br>  Nous avons la possibilit√© d'utiliser la monade Try.  En substance, il s'agit d'un conteneur qui stocke une certaine valeur.  flatMap est une m√©thode de travail avec ce conteneur, qui, avec la valeur actuelle, peut prendre une fonction et, encore une fois, retourner une monade. <br><br>  Dans ce cas, l'appel est encapsul√© dans la monade Try (nous renvoyons Try).  Il peut √™tre trait√© en un seul endroit - l√† o√π nous en avons besoin.  Si la sortie a une valeur, nous effectuons les actions suivantes avec elle, si une exception est lev√©e, nous la traitons √† la toute fin de la cha√Æne. <br><br><h4>  Gestion des exceptions fonctionnelles </h4><br>  O√π puis-je obtenir Try? <br><br>  Tout d'abord, il existe plusieurs impl√©mentations communautaires des classes Try et Either.  Vous pouvez les prendre ou m√™me √©crire une impl√©mentation vous-m√™me.  Dans l'un des projets de ¬´combat¬ª, nous avons utilis√© l'impl√©mentation Try self-made - nous avons r√©ussi avec une classe et avons fait un excellent travail. <br>  Deuxi√®mement, il y a la biblioth√®que Arrow, qui en principe ajoute beaucoup de fonctionnalit√©s √† Kotlin.  Naturellement, il y a Try and Either. <br><br>  Eh bien, en plus, la classe Result est apparue dans Kotlin 1.3, dont je parlerai plus en d√©tail plus tard. <br><br><h4>  Essayez d'utiliser la biblioth√®que Arrow comme exemple </h4><br>  La biblioth√®que Arrow nous donne une classe Try.  En fait, cela peut √™tre dans deux √©tats: Succ√®s ou √©chec: <br><br><ul><li>  Le succ√®s d'un retrait r√©ussi conservera notre valeur, </li><li>  L'√©chec stocke une exception qui s'est produite lors de l'ex√©cution d'un bloc de code. </li></ul><br>  L'appel est le suivant.  Naturellement, il est emball√© dans un try-catch r√©gulier, mais cela se produira quelque part dans notre code. <br><br><pre> <code class="plaintext hljs">sealed class Try&lt;out A&gt; { data class Success&lt;out A&gt;(val value: A) : Try&lt;A&gt;() data class Failure(val e: Throwable) : Try&lt;Nothing&gt;() companion object { operator fun &lt;A&gt; invoke(body: () -&gt; A): Try&lt;A&gt; { return try { Success(body()) } catch (e: Exception) { Failure(e) } } }</code> </pre><br>  La m√™me classe devrait impl√©menter la m√©thode flatMap, qui vous permet de passer une fonction et de renvoyer notre try monad: <br><br><pre> <code class="plaintext hljs">inline fun &lt;B&gt; map(f: (A) -&gt; B): Try&lt;B&gt; = flatMap { Success(f(it)) } inline fun &lt;B&gt; flatMap(f: (A) -&gt; TryOf&lt;B&gt;): Try&lt;B&gt; = when (this) { is Failure -&gt; this is Success -&gt; f(value) }</code> </pre><br>  √Ä quoi √ßa sert?  Afin de ne pas traiter les erreurs pour chacun des r√©sultats lorsque nous en avons plusieurs.  Par exemple, nous avons obtenu plusieurs valeurs de diff√©rents services et souhaitons les combiner.  En fait, nous pouvons avoir deux situations: soit nous les avons re√ßues et combin√©es avec succ√®s, soit quelque chose est tomb√©.  Par cons√©quent, nous pouvons effectuer les op√©rations suivantes: <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Success(value=15)</code> </pre><br>  Si les deux appels ont r√©ussi et que nous avons obtenu les valeurs, nous ex√©cutons la fonction.  S'ils √©chouent, l'√©chec revient avec une exception. <br><br>  Voici √† quoi cela ressemble en cas de chute: <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { throw RuntimeException(‚ÄúOh no!‚Äù) } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no!</code> </pre><br>  Nous avons utilis√© la m√™me fonction, mais la sortie est un √©chec d'une RuntimeException. <br><br>  De plus, la biblioth√®que Arrow vous permet d'utiliser des constructions qui sont en fait du sucre syntaxique, en particulier la liaison.  Tout de m√™me peut √™tre r√©√©crit via un flatMap s√©rie, mais la liaison vous permet de le rendre lisible. <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val result3: Try&lt;Int&gt; = Try { throw RuntimeException(‚ÄúOh no, again!‚Äù) } val sum = binding { val (one) = result1 val (two) = result2 val (three) = result3 one + two + three } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no, again!</code> </pre><br>  √âtant donn√© que l'un des r√©sultats est tomb√©, nous obtenons une erreur sur la sortie. <br><br>  Une monade similaire peut √™tre utilis√©e pour les appels asynchrones.  Par exemple, voici deux fonctions qui s'ex√©cutent de mani√®re asynchrone.  Nous combinons leurs r√©sultats de la m√™me mani√®re, sans v√©rifier s√©par√©ment leur statut: <br><br><pre> <code class="plaintext hljs">fun funA(): Try&lt;Int&gt; { return Try { 1 } } fun funB(): Try&lt;Int&gt; { Thread.sleep(3000L) return Try { 2 } } val a = GlobalScope.async { funA() } val b = GlobalScope.async { funB() } val sum = runBlocking { a.await().flatMap { one -&gt; b.await().map {two -&gt; one + two } } }</code> </pre><br>  Et voici un exemple plus ¬´de combat¬ª.  Nous avons une demande au serveur, nous la traitons, en obtenons le corps et essayons de la mapper √† notre classe, √† partir de laquelle nous retournons d√©j√† des donn√©es. <br><br><pre> <code class="plaintext hljs">fun makeRequest(request: Request): Try&lt;List&lt;ResponseData&gt;&gt; = Try { httpClient.newCall(request).execute() } .map { it.body() } .flatMap { Try { ObjectMapper().readValue(it, ParsedResponse::class.java) } } .map { it.data } fun main(args : Array&lt;String&gt;) { val response = makeRequest(RequestBody(args)) when(response) { is Try.Success -&gt; response.data.toString() is Try.Failure -&gt; response.exception.message } }</code> </pre><br>  Try-catch rendrait ce bloc beaucoup moins lisible.  Et dans ce cas, nous obtenons response.data √† la sortie, que nous pouvons traiter en fonction du r√©sultat. <br><br><h4>  R√©sultat de Kotlin 1.3 </h4><br>  Kotlin 1.3 a introduit la classe Result.  En fait, c'est quelque chose de similaire √† Try, mais avec un certain nombre de limitations.  Il est √† l'origine destin√© √† √™tre utilis√© pour diverses op√©rations asynchrones. <br><br><pre> <code class="plaintext hljs">val result: Result&lt;VeryImportantData&gt; = Result.runCatching { makeRequest() } .mapCatching { parseResponse(it) } .mapCatching { prepareData(it) } result.fold{ { data -&gt; println(‚ÄúWe have $data‚Äù) }, exception -&gt; println(‚ÄúThere is no any data, but it's your exception $exception‚Äù) } )</code> </pre><br>  Sinon, cette classe est actuellement exp√©rimentale.  Les d√©veloppeurs de langage peuvent changer sa signature, son comportement ou le supprimer compl√®tement, donc pour le moment il est interdit de l'utiliser comme valeur de retour √† partir de m√©thodes ou d'une variable.  Cependant, il peut √™tre utilis√© comme variable locale (priv√©e).  C'est-√†-dire  en fait, il peut √™tre utilis√© comme un essai de l'exemple. <br><br><h3>  Conclusions </h3><br>  Conclusions que je me suis fait: <br><br><ul><li>  la gestion des erreurs fonctionnelles dans Kotlin est simple et pratique; </li><li>  personne ne prend la peine de les traiter par le biais du try-catch dans le style classique (√† la fois cela et ce qui a droit √† la vie; √† la fois cela et cela sont pratiques); </li><li>  l'absence d'exceptions v√©rifi√©es ne signifie pas que les erreurs ne peuvent pas √™tre trait√©es; </li><li>  des exceptions non frapp√©es sur la production entra√Ænent de tristes cons√©quences. </li></ul><br>  Auteur de l'article: Alexey Shafranov, chef du groupe de travail (Java), Maxilect <br><br>  PS Nous publions nos articles sur plusieurs sites du Runet.  Abonnez-vous √† nos pages sur les <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">cha√Ænes</a> <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">VK</a> , <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">FB</a> ou <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">Telegram</a> pour d√©couvrir toutes nos publications et autres actualit√©s Maxilect. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/fr447380/">https://habr.com/ru/post/fr447380/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../fr447368/index.html">Pas seulement pour attraper les puces. Pourquoi la vitesse est si importante pour n'importe quel magasin</a></li>
<li><a href="../fr447370/index.html">Pourquoi, en raison d'un syst√®me de brevets cass√©, l'ombre de Theranos plane toujours sur nous</a></li>
<li><a href="../fr447372/index.html">La transformation informatique est in√©vitable: par o√π commencer</a></li>
<li><a href="../fr447374/index.html">Cr√©ation d'√©l√©ments d'interface par programme √† l'aide de PureLayout (Partie 2)</a></li>
<li><a href="../fr447376/index.html">Hackathon SNA 2019</a></li>
<li><a href="../fr447382/index.html">Le livre "Unity and C #. Gamedev de l'id√©e √† la mise en ≈ìuvre. 2e √©d.</a></li>
<li><a href="../fr447384/index.html">Les semi-conducteurs de puissance au service de l'√©cologie</a></li>
<li><a href="../fr447388/index.html">TL; DR-digest de l'Universit√© ITMO: admission non classique √† l'universit√©, √©v√©nements √† venir et mat√©riaux les plus int√©ressants</a></li>
<li><a href="../fr447390/index.html">Consignes de configuration d'AccelStor AFA pour VMware vSphere</a></li>
<li><a href="../fr447392/index.html">Trois probl√®mes de services pour v√©rifier la grammaire anglaise et s'ils peuvent √™tre r√©solus</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>