<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üíç ü§ôüèø ‚õ∏Ô∏è Las excepciones de Python ahora se consideran antipatr√≥n üë®‚Äçüè≠ ‚ìÇÔ∏è üíù</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="¬øQu√© son las excepciones? Por el nombre est√° claro: surgen cuando ocurre una excepci√≥n en el programa. Puede preguntar por qu√© las excepciones son un ...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Las excepciones de Python ahora se consideran antipatr√≥n</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/oleg-bunin/blog/445234/">  ¬øQu√© son las excepciones?  Por el nombre est√° claro: surgen cuando ocurre una excepci√≥n en el programa.  Puede preguntar por qu√© las excepciones son un antipatr√≥n y c√≥mo se relacionan con la escritura.  Trat√© de <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">resolverlo</a> , y ahora quiero discutir esto contigo, harazhiteli. <br><br><h2>  Problemas de excepci√≥n </h2><br>  Es dif√≠cil encontrar fallas en lo que enfrentas todos los d√≠as.  El h√°bito y la ceguera convierten los errores en caracter√≠sticas, pero tratemos de ver las excepciones con una mente abierta. <br><br><h3>  Las excepciones son dif√≠ciles de detectar </h3><br>  Hay dos tipos de excepciones: las "expl√≠citas" se crean llamando a <code>raise</code> directamente en el c√≥digo que est√° leyendo;  Los "ocultos" est√°n ocultos en las funciones, clases, m√©todos utilizados. <br><br>  El problema es que las excepciones "ocultas" son realmente dif√≠ciles de notar.  D√©jame mostrarte un ejemplo de una funci√≥n pura: <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second</code> </pre><br>  La funci√≥n simplemente divide un n√∫mero por otro, devolviendo un <code>float</code> .  Los tipos est√°n marcados y puede ejecutar algo como esto: <br><br><pre> <code class="python hljs">result = divide(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>) print(<span class="hljs-string"><span class="hljs-string">'x / y = '</span></span>, result)</code> </pre><br>  ¬øTe has dado cuenta?  De hecho, la ejecuci√≥n del programa nunca llegar√° a <code>print</code> , porque dividir 1 por 0 es una operaci√≥n imposible, generar√° un <code>ZeroDivisionError</code> .  S√≠, dicho c√≥digo es de tipo seguro, pero no se puede usar de todos modos. <br><a name="habracut"></a><br>  Para notar un problema potencial incluso en un c√≥digo tan simple y legible, uno necesita experiencia.  Cualquier cosa en Python puede dejar de funcionar con diferentes tipos de excepciones: divisi√≥n, llamadas a funciones, <code>int</code> , <code>str</code> , generadores, iteradores en bucles, acceso a atributos o claves.  Incluso <code>raise something()</code> puede provocar un bloqueo.  Adem√°s, ni siquiera menciono las operaciones de entrada y salida.  Y las <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">excepciones marcadas ya no ser√°n compatibles</a> en el futuro cercano. <br><br><h3>  Restaurar el comportamiento normal en su lugar no es posible </h3><br>  Pero precisamente para tal caso, tenemos excepciones.  Solo manejemos <code>ZeroDivisionError</code> y el c√≥digo se convertir√° en tipo seguro. <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second <span class="hljs-keyword"><span class="hljs-keyword">except</span></span> ZeroDivisionError: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-number"><span class="hljs-number">0.0</span></span></code> </pre><br>  Ahora todo est√° bien.  Pero, ¬øpor qu√© devolvemos 0?  ¬øPor qu√© no 1 o <code>None</code> ?  Por supuesto, en la mayor√≠a de los casos, obtener <code>None</code> casi tan malo (si no peor) como una excepci√≥n, pero a√∫n as√≠ debe confiar en la l√≥gica empresarial y las opciones para usar la funci√≥n. <br><br>  ¬øQu√© estamos compartiendo exactamente?  N√∫meros arbitrarios, alguna unidad espec√≠fica o dinero?  No todas las opciones son f√°ciles de prever y restaurar.  Puede resultar que la pr√≥xima vez que use una funci√≥n, resulte que necesita una l√≥gica de recuperaci√≥n diferente. <br><br><blockquote>  La triste conclusi√≥n: la soluci√≥n a cada problema es individual, dependiendo del contexto espec√≠fico de uso. </blockquote><br>  No hay una bala de plata para tratar con <code>ZeroDivisionError</code> una vez por todas.  Y no estamos hablando de la posibilidad de E / S complejas con solicitudes y tiempos de espera repetidos. <br><br>  ¬øQuiz√°s no sea necesario manejar las excepciones exactamente donde surgen?  Tal vez solo lo arroje al proceso de ejecuci√≥n del c√≥digo; alguien lo resolver√° m√°s tarde.  Y luego nos vemos obligados a volver al estado actual de las cosas. <br><br><h3>  Proceso de ejecuci√≥n poco claro </h3><br>  Bueno, esperemos que alguien m√°s detecte la excepci√≥n y tal vez la maneje.  Por ejemplo, el sistema puede pedirle al usuario que cambie el valor ingresado, porque no puede dividirse entre 0. Y la funci√≥n de <code>divide</code> no debe ser expl√≠citamente responsable de recuperarse del error. <br><br>  En este caso, debe verificar d√≥nde detectamos la excepci√≥n.  Por cierto, ¬øc√≥mo determinar exactamente d√≥nde se procesar√°?  ¬øEs posible ir al lugar correcto en el c√≥digo?  Resulta que no, <strong>es imposible</strong> . <br><br>  No es posible determinar qu√© l√≠nea de c√≥digo se ejecutar√° despu√©s de que se genere la excepci√≥n.  Se pueden manejar diferentes tipos de excepciones con diferentes opciones <code>except</code> , y se pueden <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">ignorar</a> algunas excepciones.  Y puede lanzar excepciones adicionales en otros m√≥dulos que se ejecutar√°n antes, y en general romper√° toda la l√≥gica. <br><br>  Supongamos que hay dos subprocesos independientes en una aplicaci√≥n: un subproceso normal que se ejecuta de arriba a abajo y un subproceso de excepci√≥n que se ejecuta a su gusto.  ¬øC√≥mo leer y entender este c√≥digo? <br><br>  Solo con el depurador activado en el modo "capturar todas las excepciones". <br><br><div style="text-align:center;"><img src="https://habrastorage.org/webt/8k/bn/do/8kbndolwukkaluarfk3vpexws2w.png"></div><br>  Excepciones, como el notorio <code>goto</code> , desgarran la estructura del programa. <br><br><h3>  Las excepciones no son exclusivas. </h3><br>  Veamos otro ejemplo: el c√≥digo de acceso HTTP API remoto habitual: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> requests <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">fetch_user_profile</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(user_id: int)</span></span></span><span class="hljs-function"> -&gt; 'UserProfile':</span></span> <span class="hljs-string"><span class="hljs-string">"""Fetches UserProfile dict from foreign API."""</span></span> response = requests.get(<span class="hljs-string"><span class="hljs-string">'/api/users/{0}'</span></span>.format(user_id)) response.raise_for_status() <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> response.json()</code> </pre><br>  En este ejemplo, literalmente todo puede salir mal.  Aqu√≠ hay una lista parcial de posibles errores: <br><br><ul><li>  La red puede no estar disponible y la solicitud no se ejecutar√° en absoluto. </li><li>  El servidor puede no funcionar. </li><li>  El servidor puede estar demasiado ocupado, se producir√° un tiempo de espera. </li><li>  El servidor puede requerir autenticaci√≥n. </li><li>  Una API puede no tener dicha URL. </li><li>  Un usuario inexistente puede ser transferido. </li><li>  Puede que no haya suficientes derechos. </li><li>  El servidor puede bloquearse debido a un error interno al procesar su solicitud </li><li>  El servidor puede devolver una respuesta no v√°lida o da√±ada. </li><li>  El servidor puede devolver JSON no v√°lidos que no se pueden analizar. </li></ul><br>  La lista sigue y sigue, por lo que muchos problemas potenciales se encuentran en el c√≥digo de las desafortunadas tres l√≠neas.  Podemos decir que generalmente funciona solo por casualidad, y es mucho m√°s probable que caiga con una excepci√≥n. <br><br><h2>  ¬øC√≥mo protegerte? </h2><br>  Ahora que nos hemos asegurado de que las excepciones pueden ser da√±inas para el c√≥digo, descubramos c√≥mo deshacernos de ellas.  Para escribir c√≥digo sin excepci√≥n, hay diferentes patrones. <br><br><ul><li>  Escribir en todas partes <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">except Exception: pass</a></code> .  Callej√≥n sin salida.  <strong>No lo hagas.</strong> </li><li>  Devolver <code>None</code> .  Demasiado malvado.  Como resultado, tendr√° que comenzar casi todas las l√≠neas <code>if something is not None:</code> y toda la l√≥gica se perder√° detr√°s de la basura de los controles de limpieza, o sufrir√° <code>TypeError</code> todo el tiempo.  No es una buena elecci√≥n. </li><li>  Escribir clases para casos de uso especial.  Por ejemplo, la clase base <code>User</code> con subclases para errores como <code>UserNotFound</code> y <code>MissingUser</code> .  Este enfoque se puede utilizar en algunas situaciones espec√≠ficas, como <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">AnonymousUser</a></code> en Django, pero no es realista incluir todos los posibles errores en las clases.  Tomar√° demasiado trabajo y el modelo de dominio se volver√° inimaginablemente complejo. </li><li>  Use contenedores para ajustar la variable resultante o el valor de error en un contenedor y contin√∫e trabajando con el valor del contenedor.  Es por eso que creamos el proyecto <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">@dry-python/return</a></code> .  Entonces, las funciones devuelven algo significativo, mecanografiado y seguro. </li></ul><br>  Volvamos al ejemplo de divisi√≥n, que devuelve 0 cuando ocurre un error. ¬øPodemos indicar expl√≠citamente que la funci√≥n no tuvo √©xito sin devolver un valor num√©rico espec√≠fico? <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; Result[float, ZeroDivisionError]:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Success(first / second) <span class="hljs-keyword"><span class="hljs-keyword">except</span></span> ZeroDivisionError <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> exc: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Failure(exc)</code> </pre><br>  Adjuntamos los valores en uno de los dos contenedores: <code>Success</code> o <code>Failure</code> .  Estas clases se heredan de la clase base <code>Result</code> .  Los tipos de valores empaquetados se pueden especificar en la anotaci√≥n con la funci√≥n devuelta, por ejemplo, <code>Result[float, ZeroDivisionError]</code> devuelve <code>Success[float]</code> o <code>Failure[ZeroDivisionError]</code> . <br><br>  ¬øQu√© nos da esto?  M√°s <strong>excepciones no son excepcionales, pero son problemas esperados</strong> .  Adem√°s, envolver una excepci√≥n en <code>Failure</code> resuelve un segundo problema: la complejidad de identificar posibles excepciones. <br><br><pre> <code class="python hljs"><span class="hljs-number"><span class="hljs-number">1</span></span> + divide(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>) <span class="hljs-comment"><span class="hljs-comment"># =&gt; mypy error: Unsupported operand types for + ("int" and "Result[float, ZeroDivisionError]")</span></span></code> </pre><br>  Ahora son f√°ciles de detectar.  Si ve <code>Result</code> en el c√≥digo, la funci√≥n puede generar una excepci√≥n.  E incluso sabes de antemano su tipo. <br><br>  Adem√°s, la biblioteca est√° completamente tipificada y es <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">compatible con PEP561</a> .  Es decir, mypy te avisar√° si intentas devolver algo que no coincide con el tipo declarado. <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; Result[float, ZeroDivisionError]:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Success(<span class="hljs-string"><span class="hljs-string">'Done'</span></span>) <span class="hljs-comment"><span class="hljs-comment"># =&gt; error: incompatible type "str"; expected "float" except ZeroDivisionError as exc: return Failure(0) # =&gt; error: incompatible type "int"; expected "ZeroDivisionError"</span></span></code> </pre><br><h3>  ¬øC√≥mo trabajar con contenedores? </h3><br>  Hay dos <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">m√©todos</a> : <br><br><ul><li>  <code>map</code> para funciones que devuelven valores normales; </li><li>  <code>bind</code> para funciones que devuelven otros contenedores. </li></ul><br><pre> <code class="python hljs">Success(<span class="hljs-number"><span class="hljs-number">4</span></span>).bind(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number / <span class="hljs-number"><span class="hljs-number">2</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Success(2) Success(4).map(lambda number: number + 1) # =&gt; Success(5)</span></span></code> </pre><br>  Lo bueno es que este c√≥digo lo proteger√° de los scripts fallidos, ya que <code>.bind</code> y <code>.map</code> no se ejecutar√°n para contenedores con <code>Failure</code> : <br><br><pre> <code class="python hljs">Failure(<span class="hljs-number"><span class="hljs-number">4</span></span>).bind(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number / <span class="hljs-number"><span class="hljs-number">2</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Failure(4) Failure(4).map(lambda number: number / 2) # =&gt; Failure(4)</span></span></code> </pre><br>  Ahora puede concentrarse en el proceso de ejecuci√≥n correcto y asegurarse de que el estado incorrecto no interrumpa el programa en un lugar inesperado.  Y siempre existe la oportunidad de <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">determinar el estado incorrecto, corregirlo</a> y volver al camino concebido del proceso. <br><br><pre> <code class="python hljs">Failure(<span class="hljs-number"><span class="hljs-number">4</span></span>).rescue(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number + <span class="hljs-number"><span class="hljs-number">1</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Success(5) Failure(4).fix(lambda number: number / 2) # =&gt; Success(2)</span></span></code> </pre><br>  En nuestro enfoque, "todos los problemas se resuelven individualmente" y "el proceso de ejecuci√≥n ahora es transparente".  ¬°Disfruta de la programaci√≥n que viaja sobre rieles! <br><br><h3>  Pero, ¬øc√≥mo expandir los valores de los contenedores? </h3><br>  De hecho, si trabaja con funciones que no saben nada sobre contenedores, necesita los valores mismos.  Luego puede usar los <code>.unwrap()</code> o <code>.value_or()</code> : <br><br><pre> <code class="python hljs">Success(<span class="hljs-number"><span class="hljs-number">1</span></span>).unwrap() <span class="hljs-comment"><span class="hljs-comment"># =&gt; 1 Success(0).value_or(None) # =&gt; 0 Failure(0).value_or(None) # =&gt; None Failure(1).unwrap() # =&gt; Raises UnwrapFailedError()</span></span></code> </pre><br>  Espera, tuvimos que deshacernos de las excepciones, y ahora resulta que todas las llamadas <code>.unwrap()</code> pueden conducir a otra excepci√≥n. <br><br><h3>  ¬øC√≥mo no pensar en UnwrapFailedErrors? </h3><br>  Ok, veamos c√≥mo vivir con las nuevas excepciones.  Considere este ejemplo: debe verificar la entrada del usuario y crear dos modelos en la base de datos.  Cada paso puede terminar con una excepci√≥n, raz√≥n por la cual todos los m√©todos se envuelven en <code>Result</code> : <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> <span class="hljs-comment"><span class="hljs-comment"># </span><span class="hljs-doctag"><span class="hljs-comment"><span class="hljs-doctag">TODO:</span></span></span><span class="hljs-comment"> we need to create a pipeline of these methods somehow... def _validate_user( self, username: str, email: str, ) -&gt; Result['UserSchema', str]: """Returns an UserSchema for valid input, otherwise a Failure.""" def _create_account( self, user_schema: 'UserSchema', ) -&gt; Result['Account', str]: """Creates an Account for valid UserSchema's. Or returns a Failure.""" def _create_user( self, account: 'Account', ) -&gt; Result['User', str]: """Create an User instance. If user already exists returns Failure."""</span></span></code> </pre><br>  En primer lugar, no tiene que expandir los valores en su propia l√≥gica de negocios: <br><br><pre> <code class="python hljs"><span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__call__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, username: str, email: str)</span></span></span><span class="hljs-function"> -&gt; Result['User', str]:</span></span> <span class="hljs-string"><span class="hljs-string">"""Can return a Success(user) or Failure(str_reason)."""</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> self._validate_user( username, email, ).bind( self._create_account, ).bind( self._create_user, ) <span class="hljs-comment"><span class="hljs-comment"># ...</span></span></code> </pre><br>  Todo funcionar√° sin problemas, no se generar√°n excepciones, porque <code>.unwrap()</code> no se utiliza.  ¬øPero es f√°cil leer ese c√≥digo?  No  ¬øY cu√°l es la alternativa?  <code>@pipeline</code> : <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> result.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> pipeline <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> @pipeline <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__call__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, username: str, email: str)</span></span></span><span class="hljs-function"> -&gt; Result['User', str]:</span></span> <span class="hljs-string"><span class="hljs-string">"""Can return a Success(user) or Failure(str_reason)."""</span></span> user_schema = self._validate_user(username, email).unwrap() account = self._create_account(user_schema).unwrap() <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> self._create_user(account) <span class="hljs-comment"><span class="hljs-comment"># ...</span></span></code> </pre><br>  Ahora este c√≥digo est√° bien le√≠do.  As√≠ es como <code>.unwrap()</code> y <code>@pipeline</code> trabajan juntos: cada vez que <code>.unwrap()</code> un m√©todo <code>.unwrap()</code> y <code>Failure[str]</code> , el decorador <code>@pipeline</code> lo <code>@pipeline</code> y devuelve <code>Failure[str]</code> como el valor resultante.  As√≠ es como propongo eliminar todas las excepciones del c√≥digo y hacerlo realmente seguro y escrito. <br><br><h2>  Envu√©lvelo todo </h2><br>  Bueno, ahora aplicaremos las nuevas herramientas, por ejemplo, con una solicitud a la API HTTP.  ¬øRecuerdas que cada l√≠nea puede lanzar una excepci√≥n?  Y no hay forma de hacer que devuelvan el contenedor con <code>Result</code> .  Pero puede usar el <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">decorador @safe</a> para envolver funciones inseguras y hacerlas seguras.  A continuaci√≥n hay dos opciones de c√≥digo que hacen lo mismo: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> safe @safe <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second <span class="hljs-comment"><span class="hljs-comment"># is the same as: def divide(first: float, second: float) -&gt; Result[float, ZeroDivisionError]: try: return Success(first / second) except ZeroDivisionError as exc: return Failure(exc)</span></span></code> </pre><br>  El primero, con <code>@safe</code> , es m√°s f√°cil y mejor de leer. <br><br>  Lo √∫ltimo que se debe hacer en el ejemplo de solicitud de API es agregar el decorador <code>@safe</code> .  El resultado es el siguiente c√≥digo: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> requests <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> pipeline, safe <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">FetchUserProfile</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Single responsibility callable object that fetches user profile."""</span></span> <span class="hljs-comment"><span class="hljs-comment">#: You can later use dependency injection to replace `requests` #: with any other http library (or even a custom service). _http = requests @pipeline def __call__(self, user_id: int) -&gt; Result['UserProfile', Exception]: """Fetches UserProfile dict from foreign API.""" response = self._make_request(user_id).unwrap() return self._parse_json(response) @safe def _make_request(self, user_id: int) -&gt; requests.Response: response = self._http.get('/api/users/{0}'.format(user_id)) response.raise_for_status() return response @safe def _parse_json(self, response: requests.Response) -&gt; 'UserProfile': return response.json()</span></span></code> </pre><br>  <strong>Para resumir c√≥mo deshacerse de las excepciones y asegurar el c√≥digo</strong> : <br><br><ul><li>  Use el contenedor <code>@safe</code> para todos los m√©todos que pueden <code>@safe</code> una excepci√≥n.  Cambiar√° el tipo de retorno de la funci√≥n a <code>Result[OldReturnType, Exception]</code> . </li><li>  Utilice <code>Result</code> como contenedor para transferir valores y errores en una simple abstracci√≥n. </li><li>  Use <code>.unwrap()</code> para expandir el valor del contenedor. </li><li>  Use <code>@pipeline</code> para hacer que las <code>.unwrap</code> llamadas <code>.unwrap</code> sean m√°s f√°ciles de leer. </li></ul><br>  Al observar estas reglas, podemos hacer exactamente lo mismo, solo que es seguro y f√°cil de leer.  Se resolvieron todos los problemas con excepciones: <br><br><ul><li>  <strong>"Las excepciones son dif√≠ciles de detectar"</strong> .  Ahora est√°n envueltos en un contenedor de <code>Result</code> escrito, lo que los hace completamente transparentes. </li><li>  <strong>"Restablecer el comportamiento normal en su lugar es imposible"</strong> .  Ahora puede delegar con seguridad el proceso de recuperaci√≥n a la persona que llama.  Para tal caso, hay <code>.fix()</code> y <code>.rescue()</code> . </li><li>  <strong>"La secuencia de ejecuci√≥n no est√° clara"</strong> .  Ahora son uno con el flujo comercial habitual.  De principio a fin. </li><li>  <strong>"Las excepciones no son excepcionales"</strong> .  Lo sabemos!  Y esperamos que algo salga mal y listo para cualquier cosa. </li></ul><br><h3>  Casos de uso y limitaciones </h3><br>  Obviamente, no puede usar este enfoque en todo su c√≥digo.  Ser√° <strong>demasiado seguro</strong> para la mayor√≠a de las situaciones cotidianas y es incompatible con otras bibliotecas o marcos.  Pero debe escribir las partes m√°s importantes de su l√≥gica de negocios exactamente como lo mostr√©, para garantizar el funcionamiento correcto de su sistema y facilitar el soporte futuro. <br><br><blockquote>  ¬øEl tema te hace pensar o incluso parecer holivarny?  Ven a <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">Mosc√∫ Python Conf ++</a> el 5 de abril, ¬°lo discutiremos!  Adem√°s de m√≠, Artyom Malyshev, fundador del proyecto de python seco y desarrollador principal de Django Channels, estar√° all√≠.  <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">Hablar√°</a> m√°s sobre python seco y l√≥gica de negocios. </blockquote></div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/445234/">https://habr.com/ru/post/445234/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../445220/index.html">AMD Radeon VII: Chip de gama alta (Parte 3)</a></li>
<li><a href="../445222/index.html">Obtenga una oferta en 1 d√≠a para el equipo de backend en el D√≠a de la Cosmon√°utica</a></li>
<li><a href="../445226/index.html">El desarrollo de un cohete capaz de alcanzar la luna le costar√° a Rusia 740 mil millones de rublos</a></li>
<li><a href="../445228/index.html">Criptograf√≠a en Java. Clase de Mac</a></li>
<li><a href="../445230/index.html">Comenz√≥ la inscripci√≥n para la II conferencia de TI para principiantes SMARTRHINO-2019</a></li>
<li><a href="../445236/index.html">‚ÄúExtreme NOW Forum 2019‚Äù: inscripci√≥n abierta</a></li>
<li><a href="../445238/index.html">Crece a lo grande: los 10 mejores informes de Mobius 2018 Mosc√∫</a></li>
<li><a href="../445240/index.html">¬øC√≥mo mover, cargar e integrar datos muy grandes de forma econ√≥mica y r√°pida? ¬øQu√© es la optimizaci√≥n pushdown?</a></li>
<li><a href="../445242/index.html">Experiencia con Coroutines y Retrofit2</a></li>
<li><a href="../445244/index.html">"Los juegos de dinero fuera de la cadena de bloques deben morir"</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>