<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>☝🏾 🤘🏼 🚶🏾 Handler Kesalahan Standar di RxJava2 atau mengapa RxJava menyebabkan crash aplikasi bahkan jika onError diimplementasikan 🤹🏽 👵🏼 📗</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Artikel ini akan membahas RxJava2 di RxJava2 versi 2.0.6 dan yang lebih baru. Jika seseorang bertabrakan dan tidak bisa mengetahuinya, atau sama sekal...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Handler Kesalahan Standar di RxJava2 atau mengapa RxJava menyebabkan crash aplikasi bahkan jika onError diimplementasikan</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/422611/"> Artikel ini akan membahas <code>RxJava2</code> di <code>RxJava2</code> versi <code>2.0.6</code> dan yang lebih baru.  Jika seseorang bertabrakan dan tidak bisa mengetahuinya, atau sama sekali tidak mendengar masalah ini - saya minta kucing.  Mereka mendorong terjemahan masalah dalam <code>production</code> setelah transisi dari <code>RxJava1</code> ke <code>RxJava2</code> .  Dokumen asli ditulis pada 28 Desember 2017, tetapi lebih baik untuk mencari tahu terlambat daripada tidak sama sekali. <br><div style="text-align:center;"><img src="https://habrastorage.org/webt/sh/49/yi/sh49yi0mhl6-tmfir_fdvlkmcny.png"></div><a name="habracut"></a>  Kita semua adalah pengembang yang baik dan menangkap kesalahan di <code>onError</code> ketika kita menggunakan <code>RxJava</code> .  Ini berarti bahwa kami telah melindungi diri dari gangguan aplikasi, bukan? <br><br>  <i>Tidak, tidak benar.</i> <br><br>  Di bawah ini kita akan melihat beberapa contoh di mana aplikasi akan <code>RxJava</code> karena <code>RxJava</code> , bahkan jika <code>onError</code> diimplementasikan dengan benar. <br><br><h3>  Basic Error Handler di <code>RxJava</code> </h3><br>  <code>RxJava</code> menggunakan <code>RxJavaPlugins.onError</code> sebagai pengendali kesalahan dasar.  Ini menangani semua kesalahan yang tidak bisa dikirim ke pelanggan.  Secara default, semua kesalahan dikirim ke sana, sehingga crash aplikasi kritis dapat terjadi. <br>  <a href=""><code>    2.0.6</code></a> menggambarkan perilaku ini: <br><blockquote>  Salah satu tujuan dari desain 2.x adalah kurangnya kesalahan yang hilang.  Terkadang urutan berakhir atau dibatalkan sebelum sumber meningkatkan <code>onError</code> .  Dalam hal ini, kesalahan tidak memiliki tempat untuk pergi dan dikirim ke <code>RxJavaPlugins.onError</code> <br></blockquote><br>  Jika RxJava tidak memiliki penangan kesalahan dasar, kesalahan seperti itu akan disembunyikan dari kami dan pengembang akan berada dalam kegelapan tentang potensi masalah dalam kode. <br><br>  Dimulai dengan versi <code>2.0.6</code> , <code>RxJavaPlugins.onError</code> mencoba menjadi lebih cerdas dan berbagi pustaka / kesalahan implementasi dan situasi saat kesalahan tidak dapat disampaikan.  Kesalahan yang diberikan pada kategori "bug" disebut apa adanya, sedangkan sisanya dibungkus dalam <code>UndeliverableException</code> dan kemudian dipanggil.  Anda dapat melihat semua logika ini di <a href="">sini</a> ( <code>isBug</code> dan <code>isBug</code> ). <br><br>  Salah satu kesalahan utama pemula dalam <code>RxJava</code> <code>OnErrorNotImplementedException</code> adalah <code>OnErrorNotImplementedException</code> .  Kesalahan ini terjadi jika <code>observable</code> menyebabkan kesalahan dan metode <code>onError</code> tidak diterapkan pada pelanggan.  Kesalahan ini adalah contoh kesalahan yang untuk penangan kesalahan dasar <code>RxJava</code> adalah "bug" dan tidak berubah menjadi <code>UndeliverableException</code> . <br><br><h3>  Pengecualian tidak terkirim </h3><br>  Karena kesalahan yang terkait dengan "bug" mudah diperbaiki, kami tidak akan membahasnya.  Kesalahan yang <code>RxJava</code> bungkus dalam <code>RxJava</code> lebih menarik, karena mungkin tidak selalu jelas mengapa kesalahan tidak dapat dikirim ke <code>onError</code> . <br><br>  Kasus-kasus di mana hal ini dapat terjadi tergantung pada apa yang dilakukan sumber dan pelanggan secara khusus.  Kami akan mempertimbangkan contoh-contoh di bawah ini, tetapi secara umum kami dapat mengatakan bahwa kesalahan semacam itu terjadi jika tidak ada pelanggan aktif kepada siapa kesalahan tersebut dapat disampaikan. <br><br><h3>  Contoh dengan zipWith () </h3><br>  Opsi pertama di mana Anda dapat meningkatkan <code>zipWith</code> . <br><br><pre> <code class="kotlin hljs"><span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable1 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable2 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> zipper = BiFunction&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, String&gt; { one, two -&gt; <span class="hljs-string"><span class="hljs-string">"</span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$one</span></span></span><span class="hljs-string"> - </span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$two</span></span></span><span class="hljs-string">"</span></span> } observable1.zipWith(observable2, zipper) .subscribe( { System.<span class="hljs-keyword"><span class="hljs-keyword">out</span></span>.println(it) }, { it.printStackTrace() } )</code> </pre><br>  Kami menggabungkan dua sumber bersama-sama, yang masing-masing menyebabkan kesalahan.  Apa yang kita harapkan  Kita dapat mengasumsikan bahwa <code>onError</code> akan dipanggil dua kali, tetapi ini bertentangan <a href="">dengan spesifikasi</a> <code>Reactive streams</code> . <br><blockquote>  Setelah satu panggilan ke acara terminal ( <code>onError</code> , <code>onCompelete</code> ), diperlukan bahwa tidak ada lagi panggilan yang dilakukan <br></blockquote><br>  Ternyata dengan satu panggilan ke <code>onError</code> panggilan kedua tidak lagi mungkin.  Apa yang terjadi ketika kesalahan kedua terjadi di sumber?  Ini akan dikirimkan ke <code>RxJavaPlugins.onError</code> . <br><br>  Cara mudah untuk masuk ke situasi ini adalah dengan menggunakan <code>zip</code> untuk menggabungkan panggilan jaringan (misalnya, dua panggilan <code>Retrofit</code> <code>Observable</code> ).  Jika kesalahan terjadi di kedua panggilan (misalnya, tidak ada koneksi Internet), kedua sumber akan menyebabkan kesalahan, yang pertama akan jatuh ke dalam implementasi <code>onError</code> , dan yang kedua akan dikirim ke penangan kesalahan dasar ( <code>RxJavaPlugins.onError</code> ). <br><br><h3>  Contoh ConnectableObservable tanpa pelanggan </h3><br>  <code>ConnectableObservable</code> juga dapat meningkatkan <code>UndeliverableException</code> .  Patut diingat bahwa <code>ConnectableObservable</code> memunculkan peristiwa terlepas dari keberadaan pelanggan aktif, panggil saja metode <code>connect()</code> .  Jika kesalahan terjadi di <code>ConnectableObservable</code> ketika tidak ada pelanggan, itu akan dikirimkan ke penangan kesalahan dasar. <br><br>  Berikut adalah contoh yang sangat tidak bersalah yang dapat menyebabkan kesalahan seperti itu: <br><br><pre> <code class="kotlin hljs">someApi.retrofitCall() <span class="hljs-comment"><span class="hljs-comment">//     Retrofit .publish() .connect()</span></span></code> </pre><br>  Jika <code>someApi.retrofitCall()</code> menyebabkan kesalahan (misalnya, tidak ada koneksi Internet), aplikasi akan macet karena kesalahan jaringan akan dikirim ke <code>RxJava</code> kesalahan dasar <code>RxJava</code> . <br><br>  Contoh ini tampaknya fiktif, tetapi sangat mudah untuk masuk ke situasi di mana <code>ConnectableObservable</code> masih terhubung, tetapi tidak memiliki pelanggan.  Saya menemukan ini ketika menggunakan <code>autoConnect()</code> saat memanggil API.  <code>autoConnect()</code> tidak secara otomatis menonaktifkan <code>Observable</code> .  Saya berhenti berlangganan dalam metode <code>Activity</code> <code>onStop</code> , tetapi hasil panggilan jaringan kembali setelah penghancuran <code>Activity</code> dan aplikasi <code>UndeliverableException</code> dengan <code>UndeliverableException</code> . <br><br><h3>  Menangani kesalahan </h3><br>  Jadi apa yang harus dilakukan dengan kesalahan ini? <br><br>  Langkah pertama adalah melihat kesalahan yang terjadi dan mencoba menentukan apa yang menyebabkannya.  Idealnya, jika Anda dapat memperbaiki masalah pada sumbernya untuk mencegah kesalahan dari <code>RxJavaPlugins.onError</code> ke <code>RxJavaPlugins.onError</code> . <br><br>  Solusi untuk contoh <code>zipWith</code> adalah dengan mengambil satu atau kedua sumber dan mengimplementasikan <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">salah satu metode</a> untuk menangkap kesalahan di dalamnya.  Misalnya, Anda dapat menggunakan <code>onErrorReturn</code> untuk meneruskan nilai default alih-alih kesalahan. <br><br>  Contoh <code>ConnectableObservable</code> lebih mudah untuk diperbaiki - hanya pastikan Anda memutuskan <code>Observable</code> ketika pelanggan terakhir berhenti berlangganan.  <code>autoConnect()</code> , misalnya, memiliki implementasi kelebihan beban yang mengambil fungsi yang menangkap waktu koneksi ( <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">lebih banyak dapat dilihat di sini</a> ). <br><br>  Cara lain untuk memecahkan masalah adalah mengganti handler kesalahan dasar dengan Anda sendiri.  Metode <code>RxJavaPlugins.setErrorHandler(Consumer&lt;Throwable&gt;)</code> akan membantu Anda dengan ini.  Jika ini adalah solusi yang tepat untuk Anda, Anda dapat menangkap semua kesalahan yang dikirim ke <code>RxJavaPlugins.onError</code> dan menanganinya sesuai keinginan Anda.  Solusi ini bisa sangat rumit - ingat bahwa <code>RxJavaPlugins.onError</code> menerima kesalahan dari semua aliran <code>RxJava</code> dalam aplikasi. <br><br>  Jika Anda secara manual membuat <code>Observable</code> Anda, Anda dapat memanggil <code>emitter.tryOnError()</code> alih-alih <code>emitter.tryOnError()</code> .  Metode ini melaporkan kesalahan hanya jika aliran tidak dihentikan dan memiliki pelanggan.  Ingat bahwa metode ini eksperimental. <br><br>  Moral dari artikel ini adalah Anda tidak dapat memastikan bahwa tidak ada kesalahan ketika bekerja dengan RxJava jika Anda hanya menerapkan <code>onError</code> di pelanggan.  Anda harus mengetahui situasi di mana kesalahan mungkin tidak tersedia untuk pelanggan, dan pastikan bahwa situasi ini ditangani. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/id422611/">https://habr.com/ru/post/id422611/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../id422597/index.html">Backend United # 2: Isian</a></li>
<li><a href="../id422601/index.html">Chrome 69 keluar dengan generator kata sandi acak</a></li>
<li><a href="../id422603/index.html">Sedikit lebih dekat ke kesempurnaan</a></li>
<li><a href="../id422605/index.html">Tumbuh aman sejak usia muda - program pendidikan Rostelecom dan MIPT</a></li>
<li><a href="../id422609/index.html">Penghalang Bahasa dan NLP. Mengapa chatbot tidak mengerti kami?</a></li>
<li><a href="../id422613/index.html">Cybergroup PowerPool menguasai kerentanan nol hari di Panggilan Prosedur Lokal Lanjutan</a></li>
<li><a href="../id422615/index.html">Seluruh kebenaran tentang RTOS. Artikel # 9. Penjadwal: implementasi</a></li>
<li><a href="../id422617/index.html">Seluruh kebenaran tentang RTOS. Artikel # 8. Nucleus SE: Desain dan Penyebaran Internal</a></li>
<li><a href="../id422623/index.html">Bagaimana cara mengamankan C</a></li>
<li><a href="../id422625/index.html">Kami berbicara dengan Troy Miles - programmer "Neuromancer"</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>