<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>🚆 🐪 👩‍👩‍👦 Kotlin例外及其功能 🕰️ 👩🏾‍🎤 🕺🏿</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="我们公司已经在生产中使用Kotlin两年多了。 就个人而言，大约一年前，我遇到过这种语言。 有很多话题要讨论，但是今天我们将讨论错误处理，包括功能性样式。 我将告诉您如何在Kotlin中进行操作。 



 （有关该主题的会议的照片在Taganrog公司之一的办公室举行。Maxilekt工作组（Ja...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Kotlin例外及其功能</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/maxilect/blog/447380/"> 我们公司已经在生产中使用Kotlin两年多了。 就个人而言，大约一年前，我遇到过这种语言。 有很多话题要讨论，但是今天我们将讨论错误处理，包括功能性样式。 我将告诉您如何在Kotlin中进行操作。 <br><br><img src="https://habrastorage.org/webt/mb/bh/cp/mbbhcprsketr78wg8twpwhijg0y.jpeg" alt="图片"><br><br>  <i>（有关该主题的会议的照片在Taganrog公司之一的办公室举行。Maxilekt工作组（Java）负责人Alexey Shafranov发言）</i> <br><a name="habracut"></a><br><h3> 原则上如何处理错误？ </h3><br> 我发现了几种方法： <br><br><ul><li> 您可以使用一些<b>返回值</b>作为错误事实的指针； </li><li> 您可以<b>将指标参数</b>用于相同的目的， </li><li> 输入一个<b>全局变量</b> </li><li> 处理<b>异常</b> </li><li> 添加<b>合同（DbC）</b> 。 </li></ul><br> 让我们详细介绍每个选项。 <br><br><h4> 返回值 </h4><br> 如果发生错误，则返回某个“魔术”值。 如果您曾经使用过脚本语言，那么您一定已经看过类似的结构。 <br><br> 范例1： <br><br><pre><code class="plaintext hljs">function sqrt(x) { if(x &lt; 0) return -1; else return √x; }</code> </pre> <br> 范例2： <br><br><pre> <code class="plaintext hljs">function getUser(id) { result = db.getUserById(id) if (result) return result as User else return “Can't find user ” + id }</code> </pre><br><h4> 指标参数 </h4><br> 使用传递给函数的特定参数。 通过参数返回值后，您可以查看函数内部是否存在错误。 <br><br> 一个例子： <br><br><pre> <code class="plaintext hljs">function divide(x,y,out Success) { if (y == 0) Success = false else Success = true return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4> 全局变量 </h4><br> 全局变量的工作方式大致相同。 <br><br> 一个例子： <br><br><pre> <code class="plaintext hljs">global Success = true function divide(x,y) { if (y == 0) Success = false else return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4> 例外情况 </h4><br> 我们都习惯于例外。 它们几乎在任何地方都可以使用。 <br><br> 一个例子： <br><br><pre> <code class="plaintext hljs">function divide(x,y) { if (y == 0) throw Exception() else return x/y } try{ divide(10, 0)} catch (e) {//handle exception}</code> </pre><br><h4> 合约（DbC） </h4><br> 坦白说，我从未见过这种方法。 经过长时间的搜寻，我发现Kotlin 1.3具有一个实际上允许使用合同的库。 即 您可以在传递给函数的变量上设置条件，在返回值，调用次数，从何处调用等条件上进行设置。 并且，如果满足所有条件，则认为该功能可以正常工作。 <br><br> 一个例子： <br><br><pre> <code class="plaintext hljs">function sqrt (x) pre-condition (x &gt;= 0) post-condition (return &gt;= 0) begin calculate sqrt from x end</code> </pre><br> 老实说，这个库的语法很糟糕。 也许这就是为什么我还没有看到这样的事情。 <br><br><h3>  Java中的异常 </h3><br> 让我们继续学习Java以及它从一开始就如何工作。 <br><br><img src="https://habrastorage.org/webt/gk/oo/mw/gkoomw72k7yp5mhpi9ebpt02g-i.png" alt="图片"><br><br> 设计语言时，提出了两种类型的异常： <br><br><ul><li> 检查-检查; </li><li> 未选中-未选中。 </li></ul><br> 什么是检查异常？ 从理论上讲，它们是必需的，以便人们必须检查错误。 即 如果某个已检查的异常是可能的，则必须稍后对其进行检查。 从理论上讲，这种方法应该导致没有未处理的错误，并提高了代码质量。 但实际上并非如此。 我认为每个人至少一生中都有一个空洞的渔获物。 <br><br> 为什么这会不好？ <br><br> 这是直接来自Kotlin文档的经典示例-StringBuilder中实现的JDK的接口： <br><br><pre> <code class="plaintext hljs">Appendable append(CharSequence csq) throws IOException; try { log.append(message) } catch (IOException e) { //Must be safe }</code> </pre><br> 我确信您已经遇到了很多用try-catch包装的代码，在这里catch是一个空块，因为这种情况根本就不会发生。 在许多情况下，对已检查异常的处理是通过以下方式实现的：它们只是抛出RuntimeException并将其捕获到上面的某个地方（或不捕获它……）。 <br><br><pre> <code class="plaintext hljs">try { // do something } catch (IOException e) { throw new RuntimeException(e); //  - ...</code> </pre><br><h3> 科特林有什么可能 </h3><br> 在例外方面，Kotlin编译器的不同之处在于： <br><br>  1.不区分已检查和未检查的异常。 仅检查所有异常，您可以自己决定是否捕获并处理它们。 <br><br>  2. try可用作表达式-您可以运行try块并从中返回最后一行，或者从catch块返回最后一行。 <br><br><pre> <code class="plaintext hljs">val value = try {Integer.parseInt(“lol”)} catch(e: NumberFormanException) { 4 } // </code> </pre><br>  3.引用某些对象时，也可以使用类似的构造，该构造可以为空： <br><br><pre> <code class="plaintext hljs">val s = obj.money ?: throw IllegalArgumentException(“ , ”)</code> </pre><br><h4>  Java兼容性 </h4><br>  Kotlin代码可以在Java中使用，反之亦然。 如何处理异常？ <br><br><ul><li>  Kotlin中Java的已检查异常不能被检查或声明（因为Kotlin中没有已检查异常）。 </li><li> 不需要在Java中检查来自Kotlin的可能检查异常（例如，最初来自Java的异常）。 </li><li> 如果需要检查，可以使用方法中的@Throws批注来检查异常（您必须指定此方法可以抛出哪些异常）。 上面的注释仅用于Java兼容性。 但是实际上，许多人使用它来声明这种方法原则上可以引发某种异常。 </li></ul><br><h4> 尝试捕获块的替代方法 </h4><br> 尝试捕获块具有明显的缺点。 当它出现时，部分业务逻辑将在catch中传输，并且这可以通过上述许多方法之一发生。 当业务逻辑分布在整个块或整个呼叫链中时，很难理解应用程序的工作方式。 并且可读性块本身不会添加代码。 <br><br><pre> <code class="plaintext hljs">try { HttpService.SendNotification(endpointUrl); MarkNotificationAsSent(); } catch (e: UnableToConnectToServerException) { MarkNotificationAsNotSent(); }</code> </pre><br> 有哪些选择？ <br><br> 一个选项为我们提供了一种处理异常的实用方法。 类似的实现如下所示： <br><br><pre> <code class="plaintext hljs">val result: Try&lt;Result&gt; = Try{HttpService.SendNotification(endpointUrl)} when(result) { is Success -&gt; MarkNotificationAsSent() is Failure -&gt; MarkNotificationAsNotSent() }</code> </pre><br> 我们有机会使用Try monad。 本质上，这是一个存储一些价值的容器。  flatMap是使用此容器的一种方法，该容器与当前值一起可以使用一个函数，并再次返回一个monad。 <br><br> 在这种情况下，该呼叫将包装在Try monad中（我们返回Try）。 它可以在一个我们需要的地方处理。 如果输出有一个值，我们将对其执行以下操作；如果抛出异常，则将在链的最末端进行处理。 <br><br><h4> 功能异常处理 </h4><br> 在哪里可以尝试？ <br><br> 首先，有许多Try和Either类的社区实现。 您可以接受它们甚至自己编写实现。 在其中一个“战斗”项目中，我们使用了自制的Try实施-我们管理了一个班级，并且做得很好。 <br> 其次，还有Arrow库，该库原则上为Kotlin增加了很多功能。 自然地，有Try and Either。 <br><br> 好吧，此外，Result类出现在Kotlin 1.3中，我将在后面详细讨论。 <br><br><h4> 尝试以Arrow库为例 </h4><br>  Arrow库为我们提供了一个Try类。 实际上，它可以处于两种状态：成功或失败： <br><br><ul><li> 成功取款成功将保留我们的价值， </li><li> 故障存储在执行代码块期间发生的异常。 </li></ul><br> 调用如下。 自然，它包装在常规try-catch中，但这将在我们代码内的某处发生。 <br><br><pre> <code class="plaintext hljs">sealed class Try&lt;out A&gt; { data class Success&lt;out A&gt;(val value: A) : Try&lt;A&gt;() data class Failure(val e: Throwable) : Try&lt;Nothing&gt;() companion object { operator fun &lt;A&gt; invoke(body: () -&gt; A): Try&lt;A&gt; { return try { Success(body()) } catch (e: Exception) { Failure(e) } } }</code> </pre><br> 相同的类应实现flatMap方法，该方法允许您传递函数并返回我们的try monad： <br><br><pre> <code class="plaintext hljs">inline fun &lt;B&gt; map(f: (A) -&gt; B): Try&lt;B&gt; = flatMap { Success(f(it)) } inline fun &lt;B&gt; flatMap(f: (A) -&gt; TryOf&lt;B&gt;): Try&lt;B&gt; = when (this) { is Failure -&gt; this is Success -&gt; f(value) }</code> </pre><br> 这是为了什么 当我们有多个错误时，为了不处理每个结果的错误。 例如，我们从不同的服务中获得了一些价值，并希望将它们结合起来。 实际上，我们可能有两种情况：要么我们成功接收并合并了它们，要么有些东西掉了。 因此，我们可以执行以下操作： <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Success(value=15)</code> </pre><br> 如果两个调用都成功并且我们得到了值，则执行函数。 如果它们不成功，则失败将返回异常。 <br><br> 这是如果东西掉下来的样子： <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { throw RuntimeException(“Oh no!”) } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no!</code> </pre><br> 我们使用了相同的函数，但是输出是RuntimeException的Failure。 <br><br> 另外，Arrow库允许您使用实际上是语法糖（特别是绑定）的构造。 可以通过串行flatMap重写所有相同的内容，但是绑定使您可以读取它。 <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val result3: Try&lt;Int&gt; = Try { throw RuntimeException(“Oh no, again!”) } val sum = binding { val (one) = result1 val (two) = result2 val (three) = result3 one + two + three } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no, again!</code> </pre><br> 鉴于其中一项结果下降了，我们在输出中得到了一个错误。 <br><br> 类似的monad可用于异步调用。 例如，这是两个异步运行的函数。 我们以相同的方式合并结果，而无需单独检查其状态： <br><br><pre> <code class="plaintext hljs">fun funA(): Try&lt;Int&gt; { return Try { 1 } } fun funB(): Try&lt;Int&gt; { Thread.sleep(3000L) return Try { 2 } } val a = GlobalScope.async { funA() } val b = GlobalScope.async { funB() } val sum = runBlocking { a.await().flatMap { one -&gt; b.await().map {two -&gt; one + two } } }</code> </pre><br> 这是一个更“战斗”的例子。 我们有一个对服务器的请求，我们对其进行处理，从中获取主体，然后尝试将其映射到我们已经从中返回数据的类。 <br><br><pre> <code class="plaintext hljs">fun makeRequest(request: Request): Try&lt;List&lt;ResponseData&gt;&gt; = Try { httpClient.newCall(request).execute() } .map { it.body() } .flatMap { Try { ObjectMapper().readValue(it, ParsedResponse::class.java) } } .map { it.data } fun main(args : Array&lt;String&gt;) { val response = makeRequest(RequestBody(args)) when(response) { is Try.Success -&gt; response.data.toString() is Try.Failure -&gt; response.exception.message } }</code> </pre><br> 尝试捕获将使此块的可读性大大降低。 在这种情况下，我们在输出处获得response.data，我们可以根据结果进行处理。 <br><br><h4>  Kotlin 1.3的结果 </h4><br>  Kotlin 1.3引入了Result类。 实际上，它与Try类似，但有很多限制。 它最初旨在用于各种异步操作。 <br><br><pre> <code class="plaintext hljs">val result: Result&lt;VeryImportantData&gt; = Result.runCatching { makeRequest() } .mapCatching { parseResponse(it) } .mapCatching { prepareData(it) } result.fold{ { data -&gt; println(“We have $data”) }, exception -&gt; println(“There is no any data, but it's your exception $exception”) } )</code> </pre><br> 如果没有记错的话，这个课程目前是实验性的。 语言开发人员可以更改其签名，行为或将其完全删除，因此目前禁止将其用作方法或变量的返回值。 但是，它可以用作局部（私有）变量。 即 实际上，可以从示例中尝试使用它。 <br><br><h3> 结论 </h3><br> 我为自己得出的结论： <br><br><ul><li>  Kotlin中的功能错误处理既简单又方便； </li><li> 没有人会费心地通过古典风格的尝试捕捉来处理它们（具有生命权；具有生命权；具有便利性）； </li><li> 没有检查异常并不意味着不能处理错误； </li><li> 生产中未捕获的异常会导致可悲的后果。 </li></ul><br> 文章作者：Maxilect工作组（Java）负责人Alexey Shafranov <br><br>  PS：我们在Runet的多个站点上发表文章。 订阅我们在<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=zh-CN&amp;u=">VK</a> ， <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=zh-CN&amp;u=">FB</a>或<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=zh-CN&amp;u=">Telegram频道</a>上的页面，以查找有关我们所有出版物和其他Maxilect新闻的信息。 </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/zh-CN447380/">https://habr.com/ru/post/zh-CN447380/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../zh-CN447368/index.html">不只是抓跳蚤。 为什么速度对任何商店都如此重要</a></li>
<li><a href="../zh-CN447370/index.html">为什么，由于专利制度破裂，Theranos的阴影仍然笼罩着我们</a></li>
<li><a href="../zh-CN447372/index.html">IT转型是不可避免的：从哪里开始</a></li>
<li><a href="../zh-CN447374/index.html">使用PureLayout以编程方式创建界面元素（第2部分）</a></li>
<li><a href="../zh-CN447376/index.html">SNA Hackathon 2019</a></li>
<li><a href="../zh-CN447382/index.html">《统一与C＃》一书。 Gamedev从构思到实施。 第二版</a></li>
<li><a href="../zh-CN447384/index.html">功率半导体保护生态</a></li>
<li><a href="../zh-CN447388/index.html">TL； ITMO大学的摘要：非经典的大学入学，即将发生的事件和最有趣的资料</a></li>
<li><a href="../zh-CN447390/index.html">适用于VMware vSphere的AccelStor AFA配置指南</a></li>
<li><a href="../zh-CN447392/index.html">英语语法检查服务的三个问题以及是否可以解决</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>