<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>ü§ú üë®üèª‚Äçüî¨ üíÄ Manipulador de erro padr√£o no RxJava2 ou por que o RxJava causa falhas no aplicativo, mesmo que o onError seja implementado üßî üî° üè¶</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="O artigo discutir√° UndeliverableException no RxJava2 vers√£o 2.0.6 e posterior. Se algu√©m colidiu e n√£o conseguiu descobrir ou n√£o ouviu nada sobre ess...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Manipulador de erro padr√£o no RxJava2 ou por que o RxJava causa falhas no aplicativo, mesmo que o onError seja implementado</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/422611/"> O artigo discutir√° <code>UndeliverableException</code> no <code>RxJava2</code> vers√£o <code>2.0.6</code> e posterior.  Se algu√©m colidiu e n√£o conseguiu descobrir ou n√£o ouviu nada sobre esse problema, pe√ßo um gato.  Eles solicitaram a tradu√ß√£o de problemas na <code>production</code> ap√≥s a transi√ß√£o de <code>RxJava1</code> para <code>RxJava2</code> .  O original foi escrito em 28 de dezembro de 2017, mas √© melhor descobrir tarde do que nunca. <br><div style="text-align:center;"><img src="https://habrastorage.org/webt/sh/49/yi/sh49yi0mhl6-tmfir_fdvlkmcny.png"></div><a name="habracut"></a>  Todos somos bons desenvolvedores e detectamos erros no <code>onError</code> quando usamos o <code>RxJava</code> .  Isso significa que nos protegemos de falhas de aplicativos, certo? <br><br>  <i>N√£o, n√£o √© verdade.</i> <br><br>  Abaixo, veremos alguns exemplos nos quais o aplicativo <code>RxJava</code> devido ao <code>RxJava</code> , mesmo que o <code>onError</code> implementado corretamente. <br><br><h3>  Manipulador de erro b√°sico no <code>RxJava</code> </h3><br>  <code>RxJava</code> usa <code>RxJavaPlugins.onError</code> como o manipulador de erros base.  Ele lida com todos os erros que n√£o podem ser entregues ao assinante.  Por padr√£o, todos os erros s√£o enviados a ele, para que falhas cr√≠ticas do aplicativo possam ocorrer. <br>  <a href=""><code>    2.0.6</code></a> descrevem este comportamento: <br><blockquote>  Um dos objetivos do design 2.x √© a falta de erros perdidos.  √Äs vezes, uma sequ√™ncia termina ou √© cancelada antes que a fonte aumente <code>onError</code> .  Nesse caso, o erro n√£o tem para onde ir e √© enviado para <code>RxJavaPlugins.onError</code> <br></blockquote><br>  Se o RxJava n√£o tiver um manipulador de erros b√°sico, esses erros ser√£o ocultados para n√≥s e os desenvolvedores ficar√£o no escuro sobre poss√≠veis problemas no c√≥digo. <br><br>  A partir da vers√£o <code>2.0.6</code> , <code>RxJavaPlugins.onError</code> tenta ser mais inteligente e compartilha erros de biblioteca / implementa√ß√£o e situa√ß√µes em que um erro n√£o pode ser entregue.  Os erros atribu√≠dos √† categoria de "bugs" s√£o chamados como s√£o, enquanto os demais s√£o agrupados em <code>UndeliverableException</code> e depois chamados.  Voc√™ pode ver toda essa l√≥gica <a href="">aqui</a> ( <code>isBug</code> <code>onError</code> e <code>isBug</code> ). <br><br>  Um dos principais erros dos novatos no <code>RxJava</code> <code>OnErrorNotImplementedException</code> √© o <code>OnErrorNotImplementedException</code> .  Este erro ocorre se <code>observable</code> causar um erro e o m√©todo <code>onError</code> n√£o estiver implementado no assinante.  Este erro √© um exemplo de erro que, para o manipulador de erros b√°sico, <code>RxJava</code> √© um "bug" e n√£o se transforma em uma <code>UndeliverableException</code> . <br><br><h3>  UndeliverableException </h3><br>  Como os erros relacionados a "bugs" s√£o f√°ceis de corrigir, n√£o iremos nos deter neles.  Os erros que o <code>RxJava</code> envolve em uma <code>UndeliverableException</code> s√£o mais interessantes, pois nem sempre √© √≥bvio o motivo pelo qual o erro n√£o pode ser entregue ao <code>onError</code> . <br><br>  Os casos em que isso pode acontecer dependem do que as fontes e assinantes fazem especificamente.  Consideraremos exemplos abaixo, mas, em geral, podemos dizer que esse erro ocorre se n√£o houver assinante ativo para quem o erro possa ser entregue. <br><br><h3>  Exemplo com zipWith () </h3><br>  A primeira op√ß√£o na qual voc√™ pode gerar uma <code>UndeliverableException</code> √© a <code>zipWith</code> . <br><br><pre> <code class="kotlin hljs"><span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable1 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable2 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> zipper = BiFunction&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, String&gt; { one, two -&gt; <span class="hljs-string"><span class="hljs-string">"</span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$one</span></span></span><span class="hljs-string"> - </span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$two</span></span></span><span class="hljs-string">"</span></span> } observable1.zipWith(observable2, zipper) .subscribe( { System.<span class="hljs-keyword"><span class="hljs-keyword">out</span></span>.println(it) }, { it.printStackTrace() } )</code> </pre><br>  Combinamos duas fontes juntas, cada uma delas causando um erro.  O que esperamos?  Podemos supor que <code>onError</code> ser√° chamado duas vezes, mas isso contradiz <a href="">a especifica√ß√£o de</a> <code>Reactive streams</code> . <br><blockquote>  Ap√≥s uma √∫nica chamada para um evento do terminal ( <code>onError</code> , <code>onCompelete</code> ), √© necess√°rio que n√£o sejam feitas mais chamadas <br></blockquote><br>  Acontece que, com uma √∫nica chamada para <code>onError</code> segunda chamada n√£o √© mais poss√≠vel.  O que acontece quando ocorre um segundo erro na fonte?  Ele ser√° entregue ao <code>RxJavaPlugins.onError</code> . <br><br>  Uma maneira f√°cil de entrar nessa situa√ß√£o √© usar o <code>zip</code> para combinar chamadas de rede (por exemplo, duas chamadas de <code>Retrofit</code> retornando <code>Observable</code> ).  Se ocorrer um erro nas duas chamadas (por exemplo, n√£o h√° conex√£o com a Internet), ambas as fontes causar√£o erros, a primeira delas cair√° na implementa√ß√£o <code>onError</code> e a segunda ser√° entregue ao manipulador de erros base ( <code>RxJavaPlugins.onError</code> ). <br><br><h3>  Exemplo de ConnectableObservable sem assinantes </h3><br>  <code>ConnectableObservable</code> tamb√©m pode gerar uma <code>UndeliverableException</code> .  Vale lembrar que o <code>ConnectableObservable</code> gera eventos independentemente da presen√ßa de assinantes ativos, basta chamar o m√©todo <code>connect()</code> .  Se ocorrer um erro no <code>ConnectableObservable</code> quando n√£o houver assinantes, ele ser√° entregue ao manipulador de erros base. <br><br>  Aqui est√° um exemplo bastante inocente que pode causar esse erro: <br><br><pre> <code class="kotlin hljs">someApi.retrofitCall() <span class="hljs-comment"><span class="hljs-comment">//     Retrofit .publish() .connect()</span></span></code> </pre><br>  Se <code>someApi.retrofitCall()</code> causar um erro (por exemplo, n√£o h√° conex√£o com a Internet), o aplicativo <code>RxJava</code> , pois o erro de rede ser√° entregue ao <code>RxJava</code> erros base do <code>RxJava</code> . <br><br>  Este exemplo parece fict√≠cio, mas √© muito f√°cil entrar em uma situa√ß√£o em que o <code>ConnectableObservable</code> ainda est√° conectado, mas n√£o possui assinantes.  Me deparei com isso ao usar o <code>autoConnect()</code> ao chamar uma API.  <code>autoConnect()</code> n√£o desativa automaticamente o <code>Observable</code> .  <code>onStop</code> a inscri√ß√£o no m√©todo <code>onStop</code> da <code>Activity</code> , mas o resultado da chamada de rede retornou ap√≥s a destrui√ß√£o da <code>Activity</code> e o aplicativo <code>UndeliverableException</code> com <code>UndeliverableException</code> . <br><br><h3>  Tratamento de erros </h3><br>  Ent√£o, o que fazer com esses erros? <br><br>  O primeiro passo √© examinar os erros que ocorrem e tentar determinar o que os causa.  Idealmente, se voc√™ puder corrigir o problema em sua origem para impedir que o erro seja <code>RxJavaPlugins.onError</code> ao <code>RxJavaPlugins.onError</code> . <br><br>  A solu√ß√£o para o exemplo <code>zipWith</code> √© pegar uma ou ambas as fontes e implementar <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=pt&amp;u=">um dos m√©todos</a> para detectar erros nelas.  Por exemplo, voc√™ pode usar <code>onErrorReturn</code> para passar o valor padr√£o em vez de um erro. <br><br>  O exemplo do <code>ConnectableObservable</code> √© mais simples de corrigir - basta desconectar o <code>Observable</code> quando o √∫ltimo assinante cancelar a inscri√ß√£o.  <code>autoConnect()</code> , por exemplo, possui uma implementa√ß√£o sobrecarregada que <code>autoConnect()</code> uma fun√ß√£o que captura o tempo de conex√£o ( <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=pt&amp;u=">mais pode ser visto aqui</a> ). <br><br>  Outra maneira de resolver o problema √© substituir o manipulador de erros base pelo seu.  O <code>RxJavaPlugins.setErrorHandler(Consumer&lt;Throwable&gt;)</code> o ajudar√° com isso.  Se esta √© a solu√ß√£o certa para voc√™, voc√™ pode capturar todos os erros enviados para <code>RxJavaPlugins.onError</code> e manipul√°-los como achar melhor.  Essa solu√ß√£o pode ser bastante complicada - lembre-se de que o <code>RxJavaPlugins.onError</code> recebe erros de todos os fluxos do <code>RxJava</code> no aplicativo. <br><br>  Se voc√™ criar manualmente seu <code>Observable</code> , poder√° chamar <code>emitter.tryOnError()</code> vez de <code>emitter.tryOnError()</code> .  Este m√©todo relata um erro apenas se o fluxo n√£o for encerrado e tiver assinantes.  Lembre-se de que este m√©todo √© experimental. <br><br>  A moral deste artigo √© que voc√™ n√£o pode ter certeza de que n√£o h√° erros ao trabalhar com o RxJava se voc√™ simplesmente implementou o <code>onError</code> nos assinantes.  Voc√™ deve estar ciente das situa√ß√µes em que os erros podem n√£o estar dispon√≠veis para os assinantes e garantir que essas situa√ß√µes sejam tratadas. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/pt422611/">https://habr.com/ru/post/pt422611/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../pt422597/index.html">Backend United # 2: Recheio</a></li>
<li><a href="../pt422601/index.html">Chrome 69 sai com um gerador de senha aleat√≥rio</a></li>
<li><a href="../pt422603/index.html">Um pouco mais perto da perfei√ß√£o</a></li>
<li><a href="../pt422605/index.html">Crescendo em seguran√ßa desde tenra idade - programa educacional da Rostelecom e MIPT</a></li>
<li><a href="../pt422609/index.html">Barreira lingu√≠stica e PNL. Por que os chatbots n√£o nos entendem?</a></li>
<li><a href="../pt422613/index.html">O cibergrupo do PowerPool dominou a vulnerabilidade de dia zero na chamada de procedimento local avan√ßado</a></li>
<li><a href="../pt422615/index.html">Toda a verdade sobre o RTOS. Artigo 9. Agendador: implementa√ß√£o</a></li>
<li><a href="../pt422617/index.html">Toda a verdade sobre o RTOS. Artigo 8. N√∫cleo SE: Projeto Interno e Implanta√ß√£o</a></li>
<li><a href="../pt422623/index.html">Como proteger C</a></li>
<li><a href="../pt422625/index.html">Conversamos com Troy Miles - o programador do "Neuromancer"</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>