<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>👨🏾‍🤝‍👨🏻 🚶🏾 ❗️ 使用断言的一个明显问题 ✴️ 🤹🏿 🍾</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="单元测试是任何足够大的项目的重要组成部分。 我想与您分享一个有关他们非显而易见的大规模坠落的小侦探故事。 

 首先，由于一定程度的无害提交，该项目中大约进行了150个测试，而下降测试集却不稳定。 测试未互连，测试按顺序进行。 内存中的h2数据库用作测试的数据源。 在这150个测试中，绝大多数的失败...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>使用断言的一个明显问题</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/420509/"> 单元测试是任何足够大的项目的重要组成部分。 我想与您分享一个有关他们非显而易见的大规模坠落的小侦探故事。 <br><br> 首先，由于一定程度的无害提交，该项目中大约进行了150个测试，而下降测试集却不稳定。 测试未互连，测试按顺序进行。 内存中的h2数据库用作测试的数据源。 在这150个测试中，绝大多数的失败都伴随着日志中的错误：“无法获得连接，池错误超时等待空闲对象”。 应该说在项目中执行测试时连接池的大小为1。 <br><a name="habracut"></a><br> 一小段抒情题：在项目代码中，交易会定期与流程断开连接，然后在单独的交易中执行代码，最后，交易被反向链接。 在这种情况下，将编写一个帮助程序类，其用法如下所示： <br><br><pre><code class="java hljs">TransactionRunner.run(dbDataManager(), <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> MethodTransaction() { <span class="hljs-meta"><span class="hljs-meta">@Override</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> ExecutionResult </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">runInTransaction</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">throws</span></span></span><span class="hljs-function"> Exception </span></span>{ <span class="hljs-comment"><span class="hljs-comment">// ,       return result; } );</span></span></code> </pre> <br> 分析的结果表明，在包含事务中代码调用的失败测试之后，该错误开始出现： <br><br><pre> <code class="java hljs">TransactionRunner.run(dbDataManager(), <span class="hljs-keyword"><span class="hljs-keyword">new</span></span> MethodTransaction() { <span class="hljs-meta"><span class="hljs-meta">@Override</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">public</span></span></span><span class="hljs-function"> ExecutionResult </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">runInTransaction</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">throws</span></span></span><span class="hljs-function"> Exception </span></span>{ <span class="hljs-comment"><span class="hljs-comment">// ...   // assert   assert( 1, result.getSomeNotEqualOneIntValue() ); return result; } );</span></span></code> </pre> <br> 看一下TransactionRunner类内部，方法调用将导致以下代码： <br><br><pre> <code class="java hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">protected</span></span></span><span class="hljs-function"> ExecutionResult </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">run</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> </span><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">throws</span></span></span><span class="hljs-function"> CommonException </span></span>{ Transaction outerTr = getThreadTransaction(); bindThreadTransaction(<span class="hljs-keyword"><span class="hljs-keyword">null</span></span>); <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { beginTransaction(); <span class="hljs-keyword"><span class="hljs-keyword">try</span></span> { setResult(transactionCode.runInTransaction()); } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (Exception e) { dbDataManager().rollbackTransaction(); <span class="hljs-keyword"><span class="hljs-keyword">if</span></span> (transaction.onException(<span class="hljs-keyword"><span class="hljs-keyword">this</span></span>, e)) <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> e; } dbDataManager().commitTransaction(); <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> getResult(); } <span class="hljs-keyword"><span class="hljs-keyword">catch</span></span> (Exception e) { <span class="hljs-keyword"><span class="hljs-keyword">throw</span></span> ExceptionUtil.createCommonException(e); } <span class="hljs-keyword"><span class="hljs-keyword">finally</span></span> { bindThreadTransaction(outerTr); } }</code> </pre> <br> 那么这是什么问题呢？ 问题在于，由于执行测试代码而产生的AssertionError不能从Exception继承，这意味着嵌套的事务既不回滚也不提交。 由于连接池的大小等于1，因此在尝试通过后续测试获取连接对象时，会收到相同的错误“无法获取连接，池错误超时等待空闲对象”。 <br><br> 道德：必须谨慎地将断言放在测试中，在非显而易见的情况下，尤其是在大规模崩溃的情况下，解决方案之一是检查异常处理是否将未继承自Exception的对象考虑在内。 <br><br> 在我看来，这个案子值得解决，也许这种经历对某人有用。 </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/zh-CN420509/">https://habr.com/ru/post/zh-CN420509/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../zh-CN420499/index.html">推荐系统剖析。 第一部分</a></li>
<li><a href="../zh-CN420501/index.html">RAM中的Linux：Debirf Way 2018</a></li>
<li><a href="../zh-CN420503/index.html">JS开发人员日，不同的城市和社区-一个假期</a></li>
<li><a href="../zh-CN420505/index.html">OpenAI Five将赢得The International的专业团队吗</a></li>
<li><a href="../zh-CN420507/index.html">背景：所有人及其创作者的全球互联网</a></li>
<li><a href="../zh-CN420511/index.html">在远东-阿穆尔州（Amur Region）担任IT专家</a></li>
<li><a href="../zh-CN420513/index.html">39行Python代码的付费服务的盗版副本</a></li>
<li><a href="../zh-CN420515/index.html">基于GMM-UBM模型和MAP自适应算法的数字化</a></li>
<li><a href="../zh-CN420517/index.html">FPGA整数FFT实现</a></li>
<li><a href="../zh-CN420519/index.html">科学普及</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>