<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üêù üïö üë´ Standard Error Handler in RxJava2 oder warum RxJava Anwendungsabst√ºrze verursacht, selbst wenn onError implementiert ist ü§Æ ‚õÑÔ∏è üêå</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="In diesem Artikel wird RxJava2 in RxJava2 Version 2.0.6 und RxJava2 2.0.6 . Wenn jemand zusammengesto√üen ist und es nicht herausfinden kann oder √ºberh...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Standard Error Handler in RxJava2 oder warum RxJava Anwendungsabst√ºrze verursacht, selbst wenn onError implementiert ist</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/422611/"> In diesem Artikel wird <code>RxJava2</code> in <code>RxJava2</code> Version <code>2.0.6</code> und <code>RxJava2</code> <code>2.0.6</code> .  Wenn jemand zusammengesto√üen ist und es nicht herausfinden kann oder √ºberhaupt nichts von diesem Problem geh√∂rt hat, bitte ich um eine Katze.  Sie veranlassten die √úbersetzung von Problemen in der <code>production</code> nach dem √úbergang von <code>RxJava1</code> zu <code>RxJava2</code> .  Das Original wurde am 28. Dezember 2017 geschrieben, aber es ist besser, es sp√§t herauszufinden als nie. <br><div style="text-align:center;"><img src="https://habrastorage.org/webt/sh/49/yi/sh49yi0mhl6-tmfir_fdvlkmcny.png"></div><a name="habracut"></a>  Wir sind alle gute Entwickler und fangen Fehler in <code>onError</code> wenn wir <code>RxJava</code> .  Das hei√üt, wir haben uns vor Anwendungsabst√ºrzen gesch√ºtzt, oder? <br><br>  <i>Nein, nicht wahr.</i> <br><br>  Im Folgenden werden einige Beispiele aufgef√ºhrt, in denen die Anwendung aufgrund von <code>RxJava</code> , selbst wenn <code>onError</code> korrekt implementiert ist. <br><br><h3>  Grundlegende <code>RxJava</code> in <code>RxJava</code> </h3><br>  <code>RxJava</code> verwendet <code>RxJavaPlugins.onError</code> als <code>RxJavaPlugins.onError</code> .  Es behandelt alle Fehler, die nicht an den Teilnehmer √ºbermittelt werden k√∂nnen.  Standardm√§√üig werden alle Fehler an das Programm gesendet, sodass kritische Anwendungsabst√ºrze auftreten k√∂nnen. <br>  <a href=""><code>    2.0.6</code></a> beschreiben dieses Verhalten: <br><blockquote>  Eines der Ziele des 2.x-Designs ist das Fehlen verlorener Fehler.  Manchmal endet eine Sequenz oder wird abgebrochen, bevor die Quelle <code>onError</code> .  In diesem Fall kann der Fehler nicht <code>RxJavaPlugins.onError</code> und wird an <code>RxJavaPlugins.onError</code> <br></blockquote><br>  Wenn RxJava keinen grundlegenden Fehlerbehandler hat, werden solche Fehler vor uns verborgen und die Entwickler werden √ºber m√∂gliche Probleme im Code im Dunkeln bleiben. <br><br>  Ab Version <code>2.0.6</code> versucht <code>2.0.6</code> , <code>RxJavaPlugins.onError</code> zu sein, und teilt Bibliotheks- / Implementierungsfehler und Situationen, in denen ein Fehler nicht <code>RxJavaPlugins.onError</code> werden kann.  Fehler, die der Kategorie ‚ÄûBugs‚Äú zugewiesen sind, werden <code>UndeliverableException</code> aufgerufen, w√§hrend der Rest in <code>UndeliverableException</code> und dann aufgerufen wird.  Sie k√∂nnen all diese Logik <a href="">hier sehen</a> ( <code>onError</code> und <code>isBug</code> ). <br><br>  Einer der <code>RxJava</code> Neulinge in der <code>RxJava</code> ist <code>OnErrorNotImplementedException</code> .  Dieser Fehler tritt auf, wenn <code>observable</code> einen Fehler verursacht und die <code>onError</code> Methode nicht im Abonnenten implementiert ist.  Dieser Fehler ist ein Beispiel f√ºr einen Fehler, der f√ºr den grundlegenden Fehlerbehandler <code>RxJava</code> ein "Fehler" ist und nicht zu einer <code>UndeliverableException</code> . <br><br><h3>  UndeliverableException </h3><br>  Da Fehler im Zusammenhang mit ‚ÄûFehlern‚Äú leicht zu beheben sind, werden wir uns nicht mit ihnen befassen.  Die Fehler, die <code>RxJava</code> in eine <code>RxJava</code> sind interessanter, da m√∂glicherweise nicht immer klar ist, warum der Fehler nicht an <code>onError</code> . <br><br>  Die F√§lle, in denen dies passieren kann, h√§ngen davon ab, was die Quellen und Abonnenten speziell tun.  Wir werden die folgenden Beispiele betrachten, aber im Allgemeinen k√∂nnen wir sagen, dass ein solcher Fehler auftritt, wenn es keinen aktiven Teilnehmer gibt, an den der Fehler geliefert werden kann. <br><br><h3>  Beispiel mit zipWith () </h3><br>  Die erste Option, mit der Sie eine <code>zipWith</code> k√∂nnen, ist die <code>zipWith</code> . <br><br><pre> <code class="kotlin hljs"><span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable1 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable2 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> zipper = BiFunction&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, String&gt; { one, two -&gt; <span class="hljs-string"><span class="hljs-string">"</span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$one</span></span></span><span class="hljs-string"> - </span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$two</span></span></span><span class="hljs-string">"</span></span> } observable1.zipWith(observable2, zipper) .subscribe( { System.<span class="hljs-keyword"><span class="hljs-keyword">out</span></span>.println(it) }, { it.printStackTrace() } )</code> </pre><br>  Wir kombinieren zwei Quellen miteinander, von denen jede einen Fehler verursacht.  Was erwarten wir?  Wir k√∂nnen davon ausgehen, dass <code>onError</code> zweimal aufgerufen wird, dies widerspricht jedoch <a href="">der Spezifikation f√ºr</a> <code>Reactive streams</code> . <br><blockquote>  Nach einem einzelnen Aufruf eines Terminalereignisses ( <code>onError</code> , <code>onCompelete</code> ) m√ºssen keine weiteren Anrufe mehr get√§tigt werden <br></blockquote><br>  Es stellt sich heraus, dass mit einem einzigen Aufruf von <code>onError</code> zweiter Aufruf nicht mehr m√∂glich ist.  Was passiert, wenn ein zweiter Fehler in der Quelle auftritt?  Es wird an <code>RxJavaPlugins.onError</code> geliefert. <br><br>  Eine einfache M√∂glichkeit, in diese Situation zu gelangen, besteht darin, Netzwerkanrufe mit <code>zip</code> zu kombinieren (z. B. zwei <code>Retrofit</code> Anrufe, die <code>Observable</code> ).  Wenn bei beiden Aufrufen ein Fehler auftritt (z. B. besteht keine Internetverbindung), verursachen beide Quellen Fehler, von denen die erste in die <code>onError</code> Implementierung f√§llt und die zweite an den <code>RxJavaPlugins.onError</code> ( <code>RxJavaPlugins.onError</code> ) <code>RxJavaPlugins.onError</code> . <br><br><h3>  ConnectableObservable-Beispiel ohne Abonnenten </h3><br>  <code>ConnectableObservable</code> kann auch eine <code>ConnectableObservable</code> .  Es sei daran erinnert, dass <code>ConnectableObservable</code> Ereignisse unabh√§ngig von der Anwesenheit aktiver Abonnenten <code>ConnectableObservable</code> Sie einfach die <code>connect()</code> -Methode auf.  Wenn in <code>ConnectableObservable</code> ein Fehler auftritt, wenn keine Abonnenten vorhanden sind, wird er an den <code>ConnectableObservable</code> . <br><br>  Hier ist ein ziemlich unschuldiges Beispiel, das einen solchen Fehler verursachen k√∂nnte: <br><br><pre> <code class="kotlin hljs">someApi.retrofitCall() <span class="hljs-comment"><span class="hljs-comment">//     Retrofit .publish() .connect()</span></span></code> </pre><br>  Wenn <code>someApi.retrofitCall()</code> einen Fehler verursacht (z. B. besteht keine Internetverbindung), st√ºrzt die Anwendung ab, da der Netzwerkfehler an den <code>RxJava</code> wird. <br><br>  Dieses Beispiel scheint fiktiv zu sein, aber es ist sehr einfach, in eine Situation zu geraten, in der <code>ConnectableObservable</code> noch verbunden ist, aber keine Abonnenten hat.  Ich bin darauf <code>autoConnect()</code> als <code>autoConnect()</code> beim Aufrufen einer API <code>autoConnect()</code> .  <code>autoConnect()</code> deaktiviert <code>Observable</code> nicht automatisch.  Ich habe die <code>onStop</code> <code>Activity</code> abgemeldet, aber das Ergebnis des Netzwerkaufrufs, der nach der Zerst√∂rung der <code>Activity</code> und der Anwendung <code>UndeliverableException</code> mit <code>UndeliverableException</code> . <br><br><h3>  Fehlerbehandlung </h3><br>  Was tun mit diesen Fehlern? <br><br>  Der erste Schritt besteht darin, die auftretenden Fehler zu untersuchen und festzustellen, was sie verursacht.  Ideal, wenn Sie das Problem an der Quelle beheben k√∂nnen, um zu verhindern, dass der Fehler an <code>RxJavaPlugins.onError</code> . <br><br>  Die L√∂sung f√ºr das Beispiel <code>zipWith</code> besteht darin, eine oder beide Quellen zu verwenden und <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">eine der Methoden</a> zum Abfangen von Fehlern in ihnen zu implementieren.  Beispielsweise k√∂nnen Sie <code>onErrorReturn</code> , um den Standardwert anstelle eines Fehlers zu √ºbergeben. <br><br>  Das <code>ConnectableObservable</code> Beispiel ist einfacher zu beheben. <code>ConnectableObservable</code> Sie lediglich sicher, dass Sie <code>Observable</code> trennen, wenn sich der letzte Abonnent abmeldet.  <code>autoConnect()</code> verf√ºgt beispielsweise √ºber eine √ºberladene Implementierung, die eine Funktion √ºbernimmt, die die Verbindungszeit <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">erfasst</a> ( <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">mehr finden Sie hier</a> ). <br><br>  Eine andere M√∂glichkeit, das Problem zu l√∂sen, besteht darin, den Basisfehlerbehandler durch Ihren eigenen zu ersetzen.  Die <code>RxJavaPlugins.setErrorHandler(Consumer&lt;Throwable&gt;)</code> hilft Ihnen dabei.  Wenn dies die f√ºr Sie richtige L√∂sung ist, k√∂nnen Sie alle an <code>RxJavaPlugins.onError</code> gesendeten Fehler <code>RxJavaPlugins.onError</code> und nach <code>RxJavaPlugins.onError</code> behandeln.  Diese L√∂sung kann sehr kompliziert sein - denken <code>RxJavaPlugins.onError</code> daran, dass <code>RxJavaPlugins.onError</code> Fehler von allen <code>RxJava</code> Streams in der Anwendung empf√§ngt. <br><br>  Wenn Sie Ihre <code>Observable</code> manuell erstellen, k√∂nnen Sie <code>emitter.tryOnError()</code> anstelle von <code>emitter.tryOnError()</code> .  Diese Methode meldet einen Fehler nur, wenn der Stream nicht beendet ist und Abonnenten hat.  Denken Sie daran, dass diese Methode experimentell ist. <br><br>  Die Moral dieses Artikels ist, dass Sie nicht sicher sein k√∂nnen, dass bei der Arbeit mit RxJava keine Fehler auftreten, wenn Sie einfach <code>onError</code> in Abonnenten implementiert <code>onError</code> .  Sie sollten sich der Situationen bewusst sein, in denen Abonnenten m√∂glicherweise keine Fehler zur Verf√ºgung stehen, und sicherstellen, dass diese Situationen behandelt werden. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/de422611/">https://habr.com/ru/post/de422611/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../de422597/index.html">Backend United # 2: F√ºllung</a></li>
<li><a href="../de422601/index.html">Chrome 69 verf√ºgt √ºber einen Zufallskennwortgenerator</a></li>
<li><a href="../de422603/index.html">Ein bisschen n√§her an der Perfektion</a></li>
<li><a href="../de422605/index.html">Schon in jungen Jahren einen Safe aufbauen - Bildungsprogramm von Rostelecom und MIPT</a></li>
<li><a href="../de422609/index.html">Sprachbarriere und NLP. Warum verstehen uns Chatbots nicht?</a></li>
<li><a href="../de422613/index.html">PowerPool Cybergroup hat die Zero-Day-Sicherheitsanf√§lligkeit in Advanced Local Procedure Call gemeistert</a></li>
<li><a href="../de422615/index.html">Die ganze Wahrheit √ºber RTOS. Artikel 9. Scheduler: Implementierung</a></li>
<li><a href="../de422617/index.html">Die ganze Wahrheit √ºber RTOS. Artikel 8. Nucleus SE: Internes Design und Bereitstellung</a></li>
<li><a href="../de422623/index.html">So sichern Sie C.</a></li>
<li><a href="../de422625/index.html">Wir haben mit Troy Miles gesprochen - dem Programmierer von "Neuromancer"</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>